### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by thefunkygibbon** [cby016/tplink_router#1]
I've tried to install it but i get a config error Platform error device_tracker.tplink_router- Integration 'tplink_router' not found.

also what about routers like deco m5 where there is no username to log in (just a password)?

**Comment by cby016** [comment]
Honestly I’m not sure.  I switched to a Synology router about 2 years ago.

**Comment by camui-alexandru** [comment]
Platform error device_tracker.tplink_router- Integration 'tplink_router' not found.

**Comment by thefunkygibbon** [comment]
yeah, exactly the error i'm getting.  I can't say i know enough about the structure of how to make integrations to know if the code /way of doing things has changed in HA over the past couple of years or not (plus i'm a relatively new HA user anyway). Else i'd try to troubleshoot it myself.
It just seems to be ignoring the python script in the correctly labelled folder etc.

**Comment by Rheinmetallskorpion** [comment]
I don't know if the code works but based on the error here, I've made a pull request. Just add a version key like "version": "1.0.0", to the manifest.json and restart the server. (see the pull request section for example)

**Comment by cby016** [comment]
I changed routers a while ago so I’m not sure if this still works but I merged your PR in.

**Comment by Rheinmetallskorpion** [comment]
> I changed routers a while ago so I’m not sure if this still works but I merged your PR in.

Thanks! This will save others some fuss. 

I can't test this out since I don't have a compatible router. I'm trying to make one for my type and have already completed a python script for it. I can't seem to figure out the encryption type my router has so it will less likely to be a part of this component. (unless I somehow figure it out in the future)

However, this is my first time making a hass component. It'll take me some time to make everything right. (considering I don't give up before that)

**Comment by Rheinmetallskorpion** [comment]
> I don't know if the code works but based on the error here, I've made a pull request. Just add a version key like "version": "1.0.0", to the manifest.json and restart the server. (see the pull request section for example)

BTW if it still doesn't work try removing the "tplink==0.2.1" in "requirements"

**Comment by thefunkygibbon** [comment]
getting other errors now 
like 
The system cannot restart because the configuration is not valid: Platform error device_tracker.tplink_router - Requirements for tplink_router not found: ['pyHS100==0.3.5'].
and a load relating to pyHS100 whatever that is.  guessing HA has moved on a fair bit since this component was made.

**Comment by Rheinmetallskorpion** [comment]
> getting other errors now
> like
> The system cannot restart because the configuration is not valid: Platform error device_tracker.tplink_router - Requirements for tplink_router not found: ['pyHS100==0.3.5'].
> and a load relating to pyHS100 whatever that is. guessing HA has moved on a fair bit since this component was made.

Try removing everything from the requirements section? Maybe there is no dependencies now.

**Comment by thefunkygibbon** [comment]
removed and tried to restart services again, still moans about that same thing (weirdly)

**Comment by Rheinmetallskorpion** [comment]
> removed and tried to restart services again, still moans about that same thing (weirdly)

Should restart the server externally before checking the configuration

**Comment by thefunkygibbon** [comment]
ok, done that, but now getting some nasty log entries

`2021-12-02 19:58:45 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook a60da08741c9152fbfd5da01e7f87f6e9ee70c7204b0c968b2d7b159e33daa7b

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 104, in async_handle_webhook

    response = await webhook["handler"](hass, webhook_id, request)

  File "/usr/src/homeassistant/homeassistant/components/smartthings/smartapp.py", line 506, in smartapp_webhook

    result = await manager.handle_request(data, request.headers)

  File "/usr/local/lib/python3.9/site-packages/pysmartapp/smartapp.py", line 173, in handle_request

    raise SmartAppNotRegisteredError(req.installed_app_id)

pysmartapp.errors.SmartAppNotRegisteredError: SmartApp handler for installed app '5b2e3035-6199-4131-bedb-41950b9b497a' was not found.

2021-12-02 19:58:45 ERROR (MainThread) [homeassistant.config] Invalid config for [device_tracker.tplink_router]: string value is None for dictionary value @ data['username']. Got None. (See /config/configuration.yaml, line 288). 

2021-12-02 19:58:47 WARNING (MainThread) [homeassistant.components.mqtt.alarm_control_panel] Received unexpected payload: alarm connected

**Comment by Rheinmetallskorpion** [comment]
What about your related section in configuration.yaml?

**Comment by Rheinmetallskorpion** [comment]
I managed to find another [repo](https://github.com/ericpignet/home-assistant-tplink_router) based on the same original code but with more devices supported. Unfortunately, the project seems to be abandoned for 15 months.

**Comment by thefunkygibbon** [comment]
getting this in the logs now 
```

2021-12-02 20:02:17 ERROR (SyncWorker_8) [homeassistant.loader] The custom integration 'tplink_router' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
```

**Comment by thefunkygibbon** [comment]
> What about your related section in configuration.yaml?

its the same as what is in the documentation 

```
device_tracker:
  - platform: tplink_router
    host: 192.168.0.254
    username: admin
    password: password
```
although i'm guessing that my router (a deco) wouldn't have a username , but if i omit the username it again complains about there being no username in the logs.  I can't win lol

**Comment by Rheinmetallskorpion** [comment]
It seems the version key in manifest.json is missing again. Are you using the component from the other repo? If so, just add the version key as we did here.

**Comment by thefunkygibbon** [comment]
whats the other repo?

**Comment by thefunkygibbon** [comment]
ah got it,  yes so it looks like i am already using this other (newer) repo version.  i don't get it though as it says you can leave the username blank etc in the documentation but it literally won't verify the ha config if you leave it blank.

**Comment by Rheinmetallskorpion** [comment]
You can simply put some random text in the username section if it is unnecessary .

**Comment by thefunkygibbon** [comment]
well, in that case it doesnt work as i had 'admin' in there and got a bunch of failed to log in messages.  guess it just doesnt support my hardware

**Comment by Rheinmetallskorpion** [comment]
If your hardware isn't listed there it hardly has chances to work since for whatever reason tplink decided to use significantly different structures on their router management website across different models. That's why I'm trying to make one work for me.

**Comment by Rheinmetallskorpion** [comment]
Thank god I managed to merge my script with these 2. They work perfectly for me. The core part of the code isn't outdated at all, you only need to find the respective requests for your model;-)

Good luck!
